moov-io/achgateway

pkg/models/events.go

https://github.com/moovfinancial/ach-orchestrator/pull/38 noted that the exact event to send was confusing. I forgot to expose this as a public struct.

Expose incoming models

---

.github/workflows/go.yml
internal/incoming/odfi/corrections_test.go
internal/incoming/odfi/returns_test.go
internal/service/config_test.go
internal/service/model_config.go

See https://github.com/moov-io/infra/pull/215

build: set code coverage threshold

---

internal/shards/repository.go

- ~Add `/.internal/trigger-cutoff` endpoint~
- ~Add `/.internal/trigger-inbound` endpoint~
**Update**: no longer going with the above approach. Will keep PR to merge `gosec` linter updates

gosec linter fixes

---

.github/workflows/go.yml
Makefile

See https://github.com/moov-io/infra/pull/234

build: profile Go cpu/mem usage and upload the reports

---

internal/notify/multi.go

notify: nil guard around upload Notifications

---

internal/pipeline/merging.go
internal/pipeline/merging_test.go
internal/storage/blob.go
internal/storage/file.go
internal/storage/filesystem.go
internal/storage/storage.go

TODO: more testing and descriptions

pipeline: pass filesystem operations through storage abstraction layer

---

docs/README.md

usecae updated to use case
added the word 'at'
tirggered fixed to triggered 
added the word 'to'
'intger' updated to integer
'what' happens updated to 'that' happens
added the word 'an'
compatiable updated to compatible 
setup changed to set up
'found' transfer updated to 'fund' transfer
added the word 'is'

Spelling and grammar updates

---

internal/pipeline/file_receiver.go
internal/pipeline/manual_cutoff_times.go
internal/pipeline/merging.go
internal/pipeline/pending_files_api.go
internal/storage/encryption.go
internal/storage/file.go
internal/storage/filesystem.go
internal/storage/storage.go

Issue: https://github.com/moov-io/achgateway/issues/51

pipeline: add endpoints for listing pending files prior to upload

---

internal/upload/sftp.go

- upload: record SFTP retry attempts
- upload: record UP metrics on SFTP agent init

Record SFTP retries and UP metric 

---

internal/pipeline/manual_cutoff_times.go
internal/pipeline/manual_cutoff_times_test.go

Double checking this works as expected. Adding logging for later reference.

pipeline: add a test and logging for filtering manual cutoffs

---

internal/pipeline/manual_cutoff_times.go
internal/pipeline/manual_cutoff_times_test.go

Fixes https://github.com/moov-io/achgateway/issues/87

pipeline: return the status (error) of each shard after manually triggered

---

internal/pipeline/file_receiver.go

I noticed we were emitting "nil message received" on shutdown the
exactly the same amount as messages received. This led me down an
investigation where it appeared we were keeping goroutines around.
Now we shutdown those goroutines once they're not needed to avoid
extra resources being wasted.
Fixes: https://github.com/moov-io/achgateway/issues/102

fix: stop accumulating receivers on each handled message

---

docs/config.md
internal/incoming/odfi/corrections.go
internal/incoming/odfi/prenotes.go
internal/incoming/odfi/reconciliation.go
internal/incoming/odfi/returns.go
internal/service/model_inbound.go

Issue: https://github.com/moov-io/achgateway/issues/112

feat: support filtering ODFI files by their paths

---

docs/concepts/odfi-files.md
docs/config.md
internal/environment.go
internal/incoming/odfi/incoming.go
internal/service/model_inbound.go

This was noticed in slack today after https://github.com/moov-io/achgateway/pull/116 was merged.

fix: remove filtering of incoming files by default

---

docs/config.md
docs/metrics.md
internal/environment.go
internal/environment_test.go
openapi.yaml

Fixes https://github.com/moov-io/achgateway/issues/118

feat: add ping route

---

internal/incoming/odfi/processor.go

Fixes https://github.com/moov-io/achgateway/issues/125

feat: set fileID on incoming ODFI files

---

internal/alerting/pagerduty.go

Here's what is produced now:
```
map[string]string{
"trace_1":"/Users/adam/code/src/github.com/moov-io/achgateway/internal/alerting/pagerduty_test.go:25",
"trace_2":"/usr/local/Cellar/go/1.19/libexec/src/testing/testing.go:1446",
"trace_3":"/usr/local/Cellar/go/1.19/libexec/src/runtime/asm_amd64.s:1594"
}
```

fix: cleanup stack trace within PD alerts

---

internal/shards/inmemory_repository.go
internal/shards/repository.go
internal/test/upload_test.go

chore: improve repo name to be more precise of the intention

---

internal/pipeline/aggregate.go
internal/pipeline/metrics.go

```
panic: inconsistent label cardinality: expected 1 label values but got 0 in prometheus.Labels{}
```

pipeline: fix calling of uploadFilesErrors metric

---

internal/pipeline/file_receiver.go

Previously we were always committing messages before processing (either in the kafka consumer layer or before application processing). This didn't allow users of achgateway to wait until messages were successfully handled to acknowledge messages, which can lead to unprocessed (but acknowledged) messages.

pipeline: Let .AutoCommit determine when messages are committed

---

internal/events/service_stream.go
internal/incoming/stream/publisher.go
internal/incoming/stream/publisher_test.go
internal/incoming/stream/streamtest/streamtest.go
internal/incoming/stream/subscription.go
internal/incoming/web/api_files.go

Follow up from https://github.com/moov-io/achgateway/pull/170

stream: try to extract consumer and producer errors from sarama

---

internal/pipeline/events_api.go
internal/pipeline/events_api_test.go
internal/pipeline/file_receiver.go
internal/pipeline/file_receiver_test.go
pkg/models/events.go

Issue: https://github.com/moov-io/achgateway/issues/183

feat: add API for publishing FileUploaded on isolated directories

---

go.mod
go.sum
internal/upload/sftp.go
internal/upload/sftp_test.go

Release notes https://github.com/moov-io/go-sftp/releases/tag/v0.11.0

chore: upgrade moov-io/go-sftp to v0.11.0

---

internal/test/upload_test.go

Trying to make this test more reliable at higher iteration counts.

test: count mergable files before manual upload

---

internal/service/model_sharding.go
internal/upload/filename_template_test.go

Fixes: https://github.com/moov-io/achgateway/issues/215

fix: default template should not overwrite files

---

internal/alerting/pagerduty.go

We often see multiple errors from an ODFI scheduler run which should all be grouped together and delivered as a single alert. It does no good to spam someone with 50+ alerts for the same issue.

fix: dedup PagerDuty alerts off call stack, not errors

---

internal/pipeline/file_receiver.go
internal/pipeline/file_receiver_test.go
internal/shards/inmemory_repository.go
internal/shards/repository.go

Fixes: https://github.com/moov-io/achgateway/issues/223

pipeline: fallback to shard name during lookup
