internal/incoming/web/api_files.go
internal/incoming/web/api_files_test.go
internal/pipeline/file_receiver.go

* Unmarshal received message into `Event` type
* in web API, before we publish a message to the queue, pass it to the `compliance.Protect` as the consumer expects it to be protected.
ach-orchestrator publishes messages (encrypted, etc.) of the `Event` type.  When achgateway consumes the message from the queue, it should unmarshal it into `Event` type, not into `ACHFile`.

read message body into Event type

---

internal/audittrail/storage.go
internal/audittrail/storage_blob.go
internal/audittrail/storage_blob_test.go
internal/audittrail/storage_mock.go
internal/pipeline/aggregate.go

This helps to organize uploaded files better with multiple destinations.

audittrail: save agent hostname in blob path

---

.github/workflows/go.yml
internal/httptest/certs.go
internal/incoming/odfi/cleanup_test.go
internal/incoming/odfi/download_test.go
internal/incoming/odfi/processor_test.go
internal/notify/email.go
internal/pipeline/merging.go
internal/pipeline/merging_test.go
internal/test/upload_test.go
internal/upload/ftp.go
internal/upload/sftp.go

To better secure our codebases we're going to enable [gosec via golangci-lint](https://golangci-lint.run/usage/linters/#gosec) in CI.

meta: fixup from adding gosec linter

---

.gitignore
internal/events/service_stream.go

We need to pass in the `TransformConfig` param as part of the `streamService` struct
Events being emitted are unencrypted. This patch will properly encrypt events.

Pass in config transform to stream service

---

docs/CONFIGURATION.md
go.sum
internal/audittrail/storage.go
internal/audittrail/storage_blob.go
internal/audittrail/storage_blob_test.go
internal/audittrail/storage_mock.go
internal/incoming/odfi/audit.go
internal/incoming/odfi/processor.go
internal/incoming/odfi/processor_test.go
internal/incoming/odfi/scheduler.go
internal/pipeline/aggregate.go
internal/service/model_inbound.go

This change will support storing inbound ODFI files (returns, corrections, etc) in an audittrail configuration. Doing so allows much better operational support for teams. 
Also:
- pipeline: save uploaded files under "outbound/" root path
Issue: https://github.com/moov-io/achgateway/issues/26

incoming/odfi: optionally store files in audit trail config

---

internal/audittrail/storage.go
internal/audittrail/storage_blob.go
internal/audittrail/storage_blob_test.go
internal/audittrail/storage_mock.go
internal/incoming/odfi/audit.go
internal/incoming/odfi/processor.go
internal/incoming/odfi/scheduler.go
internal/pipeline/aggregate.go
internal/transform/preupload.go

Some ODFI files arrive as partial Nacha compliant files and can't be properly marshaled, but regardless we should save those files exactly as they arrive to us. Going through a read -> write cycle could modify the file from their original bytes.

incoming/odfi: save the ODFI files exactly are they are downloaded

---

go.mod
internal/notify/email.go
internal/notify/helpers.go
internal/notify/helpers_test.go
internal/notify/slack.go
internal/service/model_notifications.go

Values in emails and slack notifications don't contain commas which can lead people to scan and mis-read values. To better present clear values let's include commas following USD's typical formatting.
To present values in a clearer manor for teams.

notify: improve formatting of values in emails and slack

---

internal/pipeline/merging.go

I noticed this when looking through logs of multiple instances. It's hard to determine which is the leader.

pipeline: log affirmatively when we are the leader

---

internal/notify/email.go
internal/service/model_notifications.go

A basic retry strategy for when emails fail to send.

notify: retry temporary email send failures

---

internal/incoming/stream/kafka.go
internal/incoming/stream/publisher.go
internal/incoming/stream/subscription.go

v2.6.0 was released Aug 3, 2020
https://kafka.apache.org/downloads#2.6.0

incoming/stream: bump min kafka version to v2.6.0

---

docs/CONFIGURATION.md
docs/README.md
go.mod
go.sum
internal/pipeline/merging.go
internal/service/model_sharding.go
internal/service/model_upload.go

This allows Shards to further control merged file behavior, such as max dollar amounts per-file.
The change as-is will be a small breaking change. Flattening batches (and these merge conditions) should be configured on a shard level. Currently they're on a global level, but each ODFI is different. 
See: https://github.com/moov-io/ach/pull/1009

pipeline: support passing ach merge conditions through

---

internal/pipeline/aggregate.go
internal/schedule/cutoff.go
internal/schedule/cutoff_test.go

Previously these events were not sent, so no notification was delivered.

fix: send cutoff Day events on holidays

---

internal/audittrail/storage_blob.go
internal/audittrail/storage_blob_test.go

Fixes: https://github.com/moov-io/achgateway/issues/106

fix: save plaintext audit files when GPG isn't configured

---

docs/ops/file-options.md
internal/pipeline/file_receiver.go
pkg/models/events.go

This is a combination of https://github.com/moov-io/achgateway/pull/137 and https://github.com/moov-io/achgateway/pull/138 to better handle/log unhandled messages. We should make it more obvious what the error is with handling the event.

pipeline: log and ack unhandled messages instead of getting stuck

---

docs/config.md
internal/pipeline/file_receiver_test.go
internal/service/model_sharding.go
internal/shards/inmemory_repository.go
internal/shards/repository.go
internal/shards/scope_shard_mapping_test.go
internal/test/upload_test.go

Rather than https://github.com/moov-io/achgateway/pull/152 what if we simplified the config syntax to avoid this bug all together?

shards: simplify config file mapping syntax

---

pkg/compliance/compliance_test.go
pkg/models/events.go

We're unable to accurately give this field with some of the current design.
Issue: https://github.com/moov-io/achgateway/issues/147

models: remove Filename from FileUploaded event

---

docs/ops/merging.md
internal/pipeline/merging.go

It's been brought up that if we're unable to "cache" files in uploaded/ then we shouldn't try to upload them.
I'm undecided with this change because if we can continue uploading then the results can be evented, on the audittrail and/or on the remote server.
However if we cannot upload elsewhere in addition to the cache then deeper problems should be fixed.

pipeline: skip uploading files after caching fails

---

pkg/compliance/encode.go
pkg/compliance/encode_test.go
pkg/models/model_transform.go

Often File events need to be compressed in Kafka messages. The defaults in Kafka are fairly low and real-world ACH files can easily exceed them. Let's offer a basic compression boolean for folks to leverage. 
Gzip has the best support in Go. bzip2 only supports reads.

feat: support gzip compression with Transforms

---

internal/environment.go
internal/incoming/stream/publisher_test.go
internal/incoming/stream/streamtest/streamtest.go
internal/incoming/stream/subscription.go
internal/pipeline/file_receiver.go
internal/pipeline/pipeline.go
internal/test/upload_test.go

We've been seeing this issue of infinite logging when the stream subscription fails. After https://github.com/moov-io/achgateway/pull/160 added reconnect logic we should verify that cycle is working.

test: verify we reconnect from flakey subscriptions

---

README.md
docs/usage/docker.md
internal/pipeline/manual_cutoff_times.go
internal/pipeline/manual_cutoff_times_test.go
internal/test/upload_test.go
openapi.yaml

We've ran into a few problems internally when accidentally not including shardNames. Either by accident or typo it is too easy to trigger all shards, which is rarely desired. It seems safer to require at least one shard name rather than default to all processing all shards.

pipeline: require shardNames when manually triggering cutoff windows

---

go.mod
go.sum
internal/incoming/stream/publisher.go
internal/pipeline/file_receiver.go
internal/pipeline/merging.go
internal/test/upload_test.go

We've been working to harden this reconnect logic due to flakey kafka brokers. This is another hardening change.

Include network errors in upload test

---

examples/getting-started/config.yml
internal/incoming/odfi/processor.go
internal/incoming/odfi/scheduler.go

Adds in the ability to have a nested directory as the source of incoming files.
Currently when processing an `inbound` folder that is a nested directory (ex: ```"inbound": "/client_directory/with/subpath"```, the processing of the files fails due to `processFile` being called with a directory instead of a specific file. This is not a fair assumption if the `InboundPath()`, `ReconciliationPath()`, etc. have any "depth" to them.  
[In other places](https://github.com/moov-io/achgateway/blob/8331bfc2686c9cd858bb75714d003b91a1dda208/internal/incoming/odfi/cleanup.go#L34) we make use explicitly of the agent's path information to determine what folders/files to operate on.  Following a similar pattern here. 
NOTE: The way that the audit folder path is constructed in `processFile` currently does …

Support nested inbound directory structures

---

docs/config.md
internal/incoming/odfi/processor.go
internal/incoming/odfi/processor_test.go
internal/incoming/odfi/scheduler.go
internal/service/model_inbound.go

Rather than hardcoding a few options let's allow the full set of configuration knobs.

incoming/odfi: allow configuration of ValidateOpts

---

Makefile
docker-compose.yml
internal/incoming/stream/publisher.go
internal/incoming/stream/publisher_test.go

We're only seeing `kafka: Failed to deliver 1 messages` from these errors right now, but we can get more details.

stream: unwrap underlying error from sarama.ProducerError

---

docker-compose.yml
internal/environment.go
internal/incoming/models.go
internal/incoming/web/api_files.go
internal/incoming/web/api_files_test.go
internal/pipeline/aggregate.go
internal/pipeline/file_receiver.go
internal/pipeline/merging.go
internal/pipeline/mock_xfer_merging.go
internal/test/upload_test.go
pkg/models/events.go

Fixes: https://github.com/moov-io/achgateway/issues/141, https://github.com/moov-io/achgateway/issues/142

feat: respond to CancelACHFile events with FileCancellationResponse

---

docs/config.md
internal/service/model_upload.go
internal/upload/sftp.go

The config documentation claims that `ClientPrivateKey` should be a filename but in reality it needs to be the raw key string. I've fixed that documentation, but also added a `ClientPrivateKeyFile` config for flexibility with sourcing the client private key from the filesystem.
Fixes an incorrect documentation statement, and allows flexibility on deployment by storing private keys on the filesystem instead of in configuration files.

Add client SFTP Key file support and fix docs

---

internal/shards/repository.go

Correctly scan shard name from the Spanner DB row returned when querying for a shard name by shard key
Currently the spanner query for a shard name is returning a string representation of the entire row instead of just the string value of the shard name.

fix(repository): correct an issue with shard querying in spanner

---

internal/service/model_upload.go

Adds new SkipChmodAfterUpload value to the SFTP config's marshal interface implementation.
To ensure the API response of the config endpoint matches the config in use.

add  to marshal interface for SFTP config

---

docs/config.md
internal/pipeline/aggregate.go
internal/service/model_sharding.go

Adds a configuration option of `on` to `cutoffs` which instructs the gateway on which days to run the cutoffs. Default behavior is the existing behavior of `banking-days` only. Any option besides `all-days` will execute only on banking days. `all-days` will execute 365 days a year.
Allow for sending files to ODFI on non-banking days./

feat: configuration for cutoffs on non-banking days

---

.github/workflows/go.yml
docs/_data/docs-menu.yml
docs/ops/cleanup.md
examples/getting-started/config.yml
go.sum
internal/pipeline/aggregate.go
internal/pipeline/cleanup.go
internal/pipeline/cleanup_test.go
internal/service/model_upload.go

Adds an optional cleanup service that automatically removes processed ACH files after a configurable retention period to prevent file descriptor exhaustion in long-running deployments. The service runs periodically, safely deleting only successfully uploaded files older than the retention duration (e.g., 24 hours).  Intended to be used alongside an audit mechanism such as GCS buckets to retain files long term. The feature is disabled by default.
TODO:

feat: Add configurable file cleanup service to prevent storage exhaustion

---

internal/notify/multi.go
internal/notify/multi_test.go

CodeQL seems to think that `%T` can expose struct fields, which it cannot.

notify: use reflect.TypeOf rather than %T
